# Generated by Django 2.1.5 on 2019-02-18 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('currency', models.CharField(choices=[('USD', '$')], default='USD', max_length=10)),
                ('client', models.CharField(max_length=200)),
                ('payment_system', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Запись оплаты',
                'verbose_name_plural': 'Записи оплаты',
                'ordering': ['-date_create'],
            },
        ),
    ]
