# Generated by Django 2.1.5 on 2019-02-18 20:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_media/')),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Deactive')], default='A', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=65)),
                ('name', models.CharField(max_length=124, unique=True)),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренд',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_media/')),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Deactive')], default='A', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=65)),
                ('name', models.CharField(max_length=124, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_media/')),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Deactive')], default='A', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=65)),
                ('name', models.CharField(max_length=124, unique=True)),
                ('features', models.CharField(blank=True, max_length=524, null=True, verbose_name='Особенности товара')),
                ('average_price', models.FloatField(help_text='Для поиска', verbose_name='Средняя цена товара')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='shop_media/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='shop_media/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Brand', verbose_name='Бренд товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-average_price'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('currency', models.CharField(choices=[('USD', '$')], default='USD', max_length=10)),
                ('size', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL')], max_length=5, null=True, verbose_name='Размер товара')),
                ('count', models.IntegerField(default=1, verbose_name='Кол-во единиц товара')),
                ('sales', models.IntegerField(default=0, verbose_name='Кол-во проданных единиц товара')),
                ('price', models.FloatField(verbose_name='Цена товара')),
                ('last_sale', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='Товар')),
            ],
            options={
                'ordering': ['-sales'],
            },
        ),
    ]
