# Generated by Django 2.1.5 on 2019-02-18 20:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('count', models.IntegerField(default=1, verbose_name='Кол-во единиц товара')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Единица заказа',
                'verbose_name_plural': 'Единицы заказа',
                'ordering': ['-price'],
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('currency', models.CharField(choices=[('USD', '$')], default='USD', max_length=10)),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя заказчика')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия заказчика')),
                ('address', models.CharField(max_length=200, verbose_name='Адресс заказчика')),
                ('country', models.CharField(max_length=200, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город заказчика')),
                ('postal_code', models.CharField(max_length=100, verbose_name='Почтовый код')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('total_price', models.FloatField(default=0, verbose_name='Итоговая цена')),
                ('email', models.EmailField(max_length=124, verbose_name='Email')),
                ('taxes', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('currency', models.CharField(choices=[('USD', '$')], default='USD', max_length=10)),
                ('name', models.CharField(max_length=124)),
                ('price', models.IntegerField()),
                ('contact', models.CharField(max_length=124)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Службы доставки',
            },
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='shipping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Shipping', verbose_name='Способ доставки'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderModel', verbose_name='Ссылка на заказ'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Variant', verbose_name='Тип товара'),
        ),
    ]
